### ISSUE TITLE
Feature request: support multiple repos for connected components

### ISSUE THREAD

**Issue by PoisonousJohn** [zeplin/cli#81]
Hi, in our company we're using a single Zeplin project (and project-level styleguide) for iOS and Android platforms. And we have separate repositories.

In the current setup, running a `zeplin connect` command results in the complete override of the existing connections.
This means in order to support documentation for both platforms, we need to keep `components.json` in some other place.

But ideally, we would like to have an option to connect components independently per platform.

So we would put two different `components.json` in each repo, and run `zeplin connect` independently

**Comment by berkcebi** [comment]
Hey @PoisonousJohn! Sorry for the hassle, that's definitely an interesting use case we'd want to support.

Since you mentioned that you have two different platforms with separate repositories, we'd recommend creating two child styleguides that are platform-specific. These child styleguides will inherit the same components from the parent styleguide. Here's how that would look like in Zeplin:
<img width="606" alt="Screen Shot 2021-01-27 at 8 38 37 PM" src="https://user-images.githubusercontent.com/447045/106090711-a957a900-60df-11eb-9826-9839a40040c4.png">

Once you have this setup, you can connect each repository to its corresponding styleguide. (This will also give you platform-specific specs, assets and integrations inside the Zeplin app.)

This setup would only work if you have two different projects for your iOS and Android designs though, since projects can be linked to one styleguide at a time. Let us know if that's not the case.

**Comment by PoisonousJohn** [comment]
Thanks for the suggestion. We'll try to set this up and get back with the results

**Comment by PoisonousJohn** [comment]
Hi, it seems this is not an option for us, as we have a project-level style guide. Also, designers will need to upload two projects at once.

I believe that we can try to build a small util on our side that will merge JSON files from multiple repositories.

**Comment by PoisonousJohn** [comment]
Hi again 👋🏻 . We managed to overcome this problem by merging jsons from different repos. But we stumbled on another issue similar to this https://github.com/zeplin/connected-components-docs/issues/25 .
Is it possible to do something about it?

We have several files which are connected to the component.
